<h1>Kontaktni Formular</h1>

<p>Kontaktujte nas odeslanim formulare nize</p>

<form method="post" id="form-email">
Vase emailova adresa <br>
<input type="email" name="email" required="required" value="<?php if (isset($_POST['email'])) echo (htmlspecialchars($_POST['email'])) ?>"/><br>
Antispam - zadejte aktualni rok <br>
<input type="text" name="rok" required="required"/><br>
<textarea name="zprava"><?php if(isset($_POST['zprava'])) echo htmlspecialchars($_POST['zprava']); ?></textarea>
<input type="submit" value="Odeslat">
</form>